version: '3.8'
services:
  elasticsearch:
    container_name: es-single
    image: docker.elastic.co/elasticsearch/elasticsearch:${ELASTIC_VERSION}
    environment:
      - node.name=es-single-node
      - cluster.name=es-single-cluster
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - es-single-data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - ${GLOBAL_NETWORK:-elastic}

  kibana:
    image: docker.elastic.co/kibana/kibana:${ELASTIC_VERSION}
    container_name: es-single-kibana
    environment:
      ELASTICSEARCH_URL: http://es-single:9200
      ELASTICSEARCH_HOSTS: http://es-single:9200
    ports:
      - 5601:5601
    networks:
      - ${GLOBAL_NETWORK:-elastic}

volumes:
  es-single-data:
    driver: local

networks:
  simra-services:
    driver: bridge
